global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "tala-sim"
    static_configs:
      - targets: ["sim-incident:9090"]
        labels:
          vertical: "incident"
      - targets: ["sim-deploy:9090"]
        labels:
          vertical: "deploy"
      - targets: ["sim-observe:9090"]
        labels:
          vertical: "observe"
      - targets: ["sim-provision:9090"]
        labels:
          vertical: "provision"
    metrics_path: "/metrics"
    scrape_timeout: 3s
